title: "Note."
description: "Live today. Not yesterday. Not tomorrow. Just today."
plugins:
  - jekyll-feed
  - jemoji
author:
  name             : "JU MYUNGHOON"
  avatar           : "us.jpg"
theme: jekyll-theme-minimal
