title: MYUNGHOON JU
description: ""
author:
  name             : "Your Name"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "myunghoonju@gmail.com"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/myunghoonju/"
plugins:
  - jekyll-feed
  - jemoji
logo: "storm_on_the_black_sea.jfif"
theme: jekyll-theme-minimal

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      img: true
include:
  - _includes
